import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import evaluate
import math

# Initialize Hugging Face metric modules
# These will silently download the metric scripts on the first run
_rouge = evaluate.load('rouge')
_bleu = evaluate.load('bleu')

def compute_classification_metrics(y_true, y_pred, average_method='weighted'):
    """
    Standardized classification metrics for the BERT Variant and GAN Discriminator.
    Using 'weighted' average handles potential class imbalances in the financial dataset.
    
    Args:
        y_true (list or array): Ground truth labels (0=Bearish, 1=Bullish, 2=Neutral)
        y_pred (list or array): Model predictions
        average_method (str): 'weighted', 'macro', or 'micro'
        
    Returns:
        dict: containing accuracy, f1, precision, and recall
    """
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average=average_method, zero_division=0
    )
    acc = accuracy_score(y_true, y_pred)
    
    return {
        'accuracy': round(acc, 4),
        'precision': round(precision, 4),
        'recall': round(recall, 4),
        'f1': round(f1, 4)
    }

def compute_generation_metrics(predictions, references):
    """
    Standardized generation metrics for the GPT Variant and GAN Generator.
    
    Args:
        predictions (list of str): The synthetic text generated by the model.
        references (list of str): The real text from the dataset to compare against.
        
    Returns:
        dict: containing ROUGE-1, ROUGE-2, ROUGE-L, and BLEU scores.
    """
    if not predictions or not references:
        raise ValueError("Predictions and references cannot be empty.")

    # Compute ROUGE
    rouge_results = _rouge.compute(predictions=predictions, references=references)
    
    # Compute BLEU
    # Note: evaluate expects references as a list of lists (multiple valid refs per prediction)
    formatted_references = [[ref] for ref in references]
    bleu_results = _bleu.compute(predictions=predictions, references=formatted_references)
    
    return {
        'rouge1': round(rouge_results.get('rouge1', 0), 4),
        'rouge2': round(rouge_results.get('rouge2', 0), 4),
        'rougeL': round(rouge_results.get('rougeL', 0), 4),
        'bleu': round(bleu_results.get('bleu', 0), 4)
    }

def calculate_perplexity(cross_entropy_loss):
    """
    Calculates perplexity from a given cross-entropy loss.
    Essential for the GPT variant evaluation.
    
    Args:
        cross_entropy_loss (float): The average loss over the evaluation dataset.
        
    Returns:
        float: The perplexity score.
    """
    try:
        return round(math.exp(cross_entropy_loss), 4)
    except OverflowError:
        return float('inf')

def format_for_matrix(model_name, class_metrics=None, gen_metrics=None, perplexity=None, time_per_epoch="TBD"):
    """
    Helper function to print out a row for your final performance matrix.
    """
    p_r_f1 = f"{class_metrics['precision']}/{class_metrics['recall']}/{class_metrics['f1']}" if class_metrics else "N/A"
    
    gen_str = []
    if gen_metrics:
        gen_str.append(f"BLEU: {gen_metrics['bleu']} | ROUGE-L: {gen_metrics['rougeL']}")
    if perplexity:
        gen_str.append(f"PPL: {perplexity}")
        
    gen_final = " | ".join(gen_str) if gen_str else "N/A"
    
    print(f"| {model_name: <12} | {p_r_f1: <22} | {gen_final: <25} | {time_per_epoch: <21} |")